#!/bin/bash

wget -q -O boost_1_54_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.54.0/boost_1_54_0.tar.gz/download
tar -xzf boost_1_54_0.tar.gz
cd boost_1_54_0/
./bootstrap.sh --prefix=/usr/local > /dev/null
#user_configFile=$(find $PWD -name user-config.jam)
#echo "using mpi ;" >> $user_configFile
n=$(cat /proc/cpuinfo | grep "cpu cores" | uniq | awk '{print $NF}')
./b2 -d0 --with=all -j $n install > /dev/null
ldconfig

wget -q -O libuv-v1.4.2.tar.gz https://github.com/libuv/libuv/archive/v1.4.2.tar.gz
tar -xzf libuv-v1.4.2.tar.gz
cd libuv-1.4.2/
sh autogen.sh
./configure
make --quiet
make install --quiet

git clone https://github.com/joyent/http-parser.git
cd http-parser/
make install --quiet

svn checkout https://svn.code.sf.net/p/cryptopp/code/trunk/c5 cryptopp --quiet
cd cryptopp/
make static dynameic
sudo make install PREFIX=/usr/local
