#!/bin/bash

wget -O boost_1_54_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.54.0/boost_1_54_0.tar.gz/download
tar -xzf boost_1_54_0.tar.gz
cd boost_1_54_0/
./bootstrap.sh --prefix=/usr/local
#user_configFile=$(find $PWD -name user-config.jam)
#echo "using mpi ;" >> $user_configFile
n=$(cat /proc/cpuinfo | grep "cpu cores" | uniq | awk '{print $NF}')
./b2 -d0 --with=all -j $n install
ldconfig

wget -O libuv-v1.4.2.tar.gz https://github.com/libuv/libuv/archive/v1.4.2.tar.gz
tar -xzf libuv-v1.4.2.tar.gz
cd libuv-1.4.2/
sh autogen.sh
./configure
make
make install

wget -O http-parser-v2.4.2.tar.gz https://github.com/joyent/http-parser/archive/v2.4.2.tar.gz
tar -xzf http-parser-v2.4.2.tar.gz
cd http-parser-2.4.2/
make install

